name:         fused-effects-logger
version:      0.0.0.0
license:      GPL-3
license-file: LICENSE
author:       drlkf
maintainer:   drlkf@drlkf.net
copyright:    2025 drlkf
category:     Effect
github:       haskell-github-trust/megaparsec-time
homepage:     https://github.com/drlkf/fused-effects-logger
bug-reports:  https://github.com/drlkf/fused-effects-logger/issues
tested-with:
  - GHC == 9.10
  - GHC == 9.8
  - GHC == 9.6

extra-source-files:
  - README.md

synopsis: Logger effect for the `fused-effects` library
description: >-
  A logger effect for the `fused-effects` library based on the `monad-logger`
  api.

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.12 && < 1
  - fused-effects >= 1.1 && < 2
  - monad-logger >= 0.3 && < 1

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  fused-effects-logger-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - hspec-discover
    dependencies:
      - fused-effects-logger
      - directory
      - filepath
      - ghc-prim
      - hspec
