name:       fused-effects-logger
version:    0.0.0.0
license:    GPL-3
author:     drlkf
maintainer: drlkf@drlkf.net
copyright:  2025 drlkf
category:   Effect

extra-source-files:
  - README.md

synopsis: Logger effect for the `fused-effects` library
description: >-
  A logger effect for the `fused-effects` library based on the `monad-logger`
  api.

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.12 && < 1
  - fused-effects >= 1.1 && < 2
  - monad-logger >= 0.3 && < 1

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  fused-effects-logger-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fused-effects-logger
      - directory
      - ghc-prim
      - hspec
